branches:
  only:
  - stable

language: node_js
node_js:
 - "8"

script: npm run build

cache:
  directories:
    - node_modules
    - .cache

before_deploy: pip install --user awscli
deploy:
  provider: script
  script: ~/.local/bin/aws s3 sync build s3://ottplayer-static --region=us-east-1 --delete
  skip_cleanup: true
